version: '2'

services:
  elasticsearch6:
    image: elasticsearch:6.5.4
    container_name: elasticsearch6
    environment:
      - TZ=Asia/Taipei
      - discovery.type=single-node
    ports: 
      - 9200:9200
      - 9300:9300
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - $PWD/es-data:/usr/share/elasticsearch/data/node